services:
  backend:
    build:
      context: ./backend # The folder that will be the "build context"
      dockerfile: dockerfile # Name of Dockerfile inside that folder
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend/app/dev.sqlite3:/remindme_backend/app/dev.sqlite3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "8080:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
